from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('at_device', src, depend = ['PKG_USING_MY_AT_DEVICE'], CPPPATH = CPPPATH)

Return('group')
